<?php
// auto-generated by sfPropelAdmin
// date: 2008/11/09 22:27:51
?>
<ul class="sf_admin_actions">
      <li><?php echo button_to(__('Agregar Rol'), 'rol/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
  </ul>
