<?php
// auto-generated by sfPropelAdmin
// date: 2008/11/09 22:27:51
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1 class='title-01'><?php echo __('Información de Rol %%name%%', 
array('%%name%%' => $rol->getName())) ?></h1>

<div id="sf_admin_header">
<?php include_partial('rol/edit_header', array('rol' => $rol)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('rol/edit_messages', array('rol' => $rol, 'labels' => $labels)) ?>
<?php include_partial('rol/edit_form', array('rol' => $rol, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('rol/edit_footer', array('rol' => $rol)) ?>
</div>

</div>
