<?php
// auto-generated by sfPropelAdmin
// date: 2008/12/03 02:37:37
?>
<?php echo form_tag('formu/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($formulario, 'getIdForm') ?>

<fieldset id="sf_fieldset_edicion_de_accesibilidad_de_formulario" class="">
<h2><?php echo __('Edicion de accesibilidad de formulario') ?></h2>


<div class="form-row">
  <?php echo label_for('formulario[pagina]', __($labels['formulario{pagina}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('formulario{pagina}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('formulario{pagina}')): ?>
    <?php echo form_error('formulario{pagina}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($formulario, 'getPagina', array (
  'size' => 45,
  'control_name' => 'formulario[pagina]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('formulario[credencial]', __($labels['formulario{credencial}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('formulario{credencial}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('formulario{credencial}')): ?>
    <?php echo form_error('formulario{credencial}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($formulario, 'getCredencial', array (
  'size' => 45,
  'control_name' => 'formulario[credencial]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('formulario' => $formulario)) ?>
<form>
</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($formulario->getIdForm()): ?>
<?php echo button_to(__('eliminar'), 'formu/delete?id_form='.$formulario->getIdForm(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
