<?php
// auto-generated by sfPropelAdmin
// date: 2008/12/03 02:37:37
?>
<?php use_helper('Object') ?>

<div class="sf_admin_filters">
<?php echo form_tag('formu/list', array('method' => 'get')) ?>
<form>
  <fieldset>
    <h2><?php echo __('Búsquedas') ?></h2>
    <div class="form-row">
    <label for="filters_pagina"><?php echo __('pagina:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[pagina]', isset($filters['pagina']) ? $filters['pagina'] : null, array (
  'size' => 15,
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="filters_credencial"><?php echo __('nombre del credencial:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[credencial]', isset($filters['credencial']) ? $filters['credencial'] : null, array (
  'size' => 15,
)) ?>
    </div>
    </div>

      </fieldset>

  <ul class="sf_admin_actions">
    <li><?php echo button_to(__('Limpiar'), 'formu/list?filter=filter', 'class=sf_admin_action_reset_filter') ?></li>
    <li><?php echo submit_tag(__('Filtrar'), 'name=filter class=sf_admin_action_filter') ?></li>
  </ul>

</form>
</div>
