<?php
// auto-generated by sfPropelAdmin
// date: 2008/12/03 02:37:37
?>
<td colspan="2">
    <?php echo $formulario->getPagina() ?>
     - 
    <?php echo $formulario->getCredencial() ?>
     - 
</td>