<?php
// auto-generated by sfPropelAdmin
// date: 2008/12/03 02:37:37
?>
  <th id="sf_admin_list_th_pagina">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/formulario/sort') == 'pagina'): ?>
      <?php echo link_to(__('pagina'), 'formu/list?sort=pagina&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/formulario/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/formulario/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('pagina'), 'formu/list?sort=pagina&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_credencial">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/formulario/sort') == 'credencial'): ?>
      <?php echo link_to(__('nombre del credencial'), 'formu/list?sort=credencial&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/formulario/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/formulario/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('nombre del credencial'), 'formu/list?sort=credencial&type=asc') ?>
      <?php endif; ?>
          </th>
