<?php
// auto-generated by sfPropelAdmin
// date: 2008/12/03 02:37:37
?>
<ul class="sf_admin_actions">
      <li><?php echo button_to(__('Agregar Pagina'), 'formu/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
  </ul>
