<?php
// auto-generated by sfPropelAdmin
// date: 2008/12/03 02:37:37
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Informacion de pagina %%pagina%%', 
array('%%pagina%%' => $formulario->getPagina())) ?></h1>

<div id="sf_admin_header">
<?php include_partial('formu/edit_header', array('formulario' => $formulario)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('formu/edit_messages', array('formulario' => $formulario, 'labels' => $labels)) ?>
<?php include_partial('formu/edit_form', array('formulario' => $formulario, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('formu/edit_footer', array('formulario' => $formulario)) ?>
</div>

</div>
