<?php
// auto-generated by sfPropelAdmin
// date: 2008/11/18 22:36:05
?>
<?php echo form_tag('user/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
  'onsubmit'  => 'double_list_submit(); return true;'
)) ?>

<?php echo object_input_hidden_tag($usuario, 'getIdUsuario') ?>

<fieldset id="sf_fieldset_informacion_principal" class="">
<h2><?php echo __('Informacion Principal') ?></h2>


<div class="form-row">
  <?php echo label_for('usuario[login]', __($labels['usuario{login}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('usuario{login}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('usuario{login}')): ?>
    <?php echo form_error('usuario{login}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($usuario, 'getLogin', array (
  'size' => 45,
  'control_name' => 'usuario[login]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('usuario[password]', __($labels['usuario{password}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('usuario{password}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('usuario{password}')): ?>
    <?php echo form_error('usuario{password}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($usuario, 'getPassword', array (
  'size' => 45,
  'control_name' => 'usuario[password]',
  'type' => 'password',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('usuario[nombre]', __($labels['usuario{nombre}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('usuario{nombre}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('usuario{nombre}')): ?>
    <?php echo form_error('usuario{nombre}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($usuario, 'getNombre', array (
  'size' => 45,
  'control_name' => 'usuario[nombre]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('usuario[apellidos]', __($labels['usuario{apellidos}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('usuario{apellidos}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('usuario{apellidos}')): ?>
    <?php echo form_error('usuario{apellidos}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($usuario, 'getApellidos', array (
  'size' => 45,
  'control_name' => 'usuario[apellidos]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_informaci__n_secundaria" class="">
<h2><?php echo __('Información Secundaria') ?></h2>


<div class="form-row">
  <?php echo label_for('usuario[is_active]', __($labels['usuario{is_active}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('usuario{is_active}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('usuario{is_active}')): ?>
    <?php echo form_error('usuario{is_active}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_checkbox_tag($usuario, 'getIsActive', array (
  'control_name' => 'usuario[is_active]',
  'type' => 'checkbox',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('usuario[created_at]', __($labels['usuario{created_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('usuario{created_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('usuario{created_at}')): ?>
    <?php echo form_error('usuario{created_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($usuario, 'getCreatedAt', array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'usuario[created_at]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_clave_de_respaldo" class="">
<h2><?php echo __('Clave de Respaldo') ?></h2>


<div class="form-row">
  <?php echo label_for('usuario[remenber_key]', __($labels['usuario{remenber_key}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('usuario{remenber_key}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('usuario{remenber_key}')): ?>
    <?php echo form_error('usuario{remenber_key}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($usuario, 'getRemenberKey', array (
  'control_name' => 'usuario[remenber_key]',
  'class' => 'foo',
  
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_rol_del_usuario" class="">
<h2><?php echo __('Rol del usuario') ?></h2>


<div class="form-row">
  <?php echo label_for('usuario[id_rol]', __($labels['usuario{id_rol}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('usuario{id_rol}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('usuario{id_rol}')): ?>
    <?php echo form_error('usuario{id_rol}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($usuario, 'getIdRol', array (
  'related_class' => 'Rol',
  'control_name' => 'usuario[id_rol]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_grupos" class="">
<h2><?php echo __('Grupos') ?></h2>


<div class="form-row">
  <?php echo label_for('usuario[grupos]', __($labels['usuario{grupos}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('usuario{grupos}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('usuario{grupos}')): ?>
    <?php echo form_error('usuario{grupos}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_admin_double_list($usuario, 'getGrupos', array (
  'control_name' => 'usuario[grupos]',
  'through_class' => 'UserGroup',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('usuario' => $usuario)) ?>
<form>
</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($usuario->getIdUsuario()): ?>
<?php echo button_to(__('Eliminar Usuario'), 'user/delete?id_usuario='.$usuario->getIdUsuario(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
