<?php
// auto-generated by sfPropelAdmin
// date: 2008/11/18 22:36:05
?>
<ul class="sf_admin_actions">
    <li><?php echo button_to(__('Listar'), 'user/list?id_usuario='.$usuario->getIdUsuario(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
    <li><?php echo submit_tag(__('Guardar'), array (
  'name' => 'save',
  'class' => 'sf_admin_action_save',
)) ?></li>
    <li><?php echo submit_tag(__('Guardar y Listar'), array (
  'name' => 'save_and_list',
  'class' => 'sf_admin_action_save_and_list',
)) ?></li>
  </ul>
