<?php
// auto-generated by sfPropelAdmin
// date: 2008/11/18 22:36:05
?>
    <td><?php echo $usuario->getLogin() ?></td>
      <td><?php echo $usuario->getRol() ?></td>
      <td><?php echo ($usuario->getCreatedAt() !== null && $usuario->getCreatedAt() !== '') ? format_date($usuario->getCreatedAt(), "f") : '' ?></td>
      <td><?php echo ($usuario->getUltimaEntrada() !== null && $usuario->getUltimaEntrada() !== '') ? format_date($usuario->getUltimaEntrada(), "D") : '' ?></td>
      <td><?php echo ($usuario->getUpdatedAt() !== null && $usuario->getUpdatedAt() !== '') ? format_date($usuario->getUpdatedAt(), "f") : '' ?></td>
      <td><?php echo $usuario->getRemenberkey() ?></td>
  