<?php
// auto-generated by sfPropelAdmin
// date: 2008/11/18 22:36:05
?>
<td colspan="6">
    <?php echo $usuario->getLogin() ?>
     - 
    <?php echo $usuario->getRol() ?>
     - 
    <?php echo ($usuario->getCreatedAt() !== null && $usuario->getCreatedAt() !== '') ? format_date($usuario->getCreatedAt(), "f") : '' ?>
     - 
    <?php echo ($usuario->getUltimaEntrada() !== null && $usuario->getUltimaEntrada() !== '') ? format_date($usuario->getUltimaEntrada(), "D") : '' ?>
     - 
    <?php echo ($usuario->getUpdatedAt() !== null && $usuario->getUpdatedAt() !== '') ? format_date($usuario->getUpdatedAt(), "f") : '' ?>
     - 
    <?php echo $usuario->getRemenberkey() ?>
     - 
</td>