<?php
// auto-generated by sfPropelAdmin
// date: 2008/11/18 22:36:05
?>
  <th id="sf_admin_list_th_login">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/usuario/sort') == 'login'): ?>
      <?php echo link_to(__('Nombre de usuario'), 'user/list?sort=login&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/usuario/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/usuario/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Nombre de usuario'), 'user/list?sort=login&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_rol">
        <?php echo __('Rol') ?>
          </th>
  <th id="sf_admin_list_th_created_at">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/usuario/sort') == 'created_at'): ?>
      <?php echo link_to(__('Fecha de creación'), 'user/list?sort=created_at&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/usuario/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/usuario/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Fecha de creación'), 'user/list?sort=created_at&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_ultima_entrada">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/usuario/sort') == 'ultima_entrada'): ?>
      <?php echo link_to(__('Ultima entrada'), 'user/list?sort=ultima_entrada&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/usuario/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/usuario/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Ultima entrada'), 'user/list?sort=ultima_entrada&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_updated_at">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/usuario/sort') == 'updated_at'): ?>
      <?php echo link_to(__('Fecha de modificación'), 'user/list?sort=updated_at&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/usuario/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/usuario/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Fecha de modificación'), 'user/list?sort=updated_at&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_remenberkey">
        <?php echo __('Remenberkey') ?>
          </th>
