<?php
// auto-generated by sfPropelAdmin
// date: 2008/11/18 22:36:05
?>
<ul class="sf_admin_actions">
      <li><?php echo button_to(__('Agregar un Usuario'), 'user/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
  </ul>
