<?php
// auto-generated by sfPropelAdmin
// date: 2008/11/18 22:36:05
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Información de Usuario %%login%%', 
array('%%login%%' => $usuario->getLogin())) ?></h1>

<div id="sf_admin_header">
<?php include_partial('user/edit_header', array('usuario' => $usuario)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('user/edit_messages', array('usuario' => $usuario, 'labels' => $labels)) ?>
<?php include_partial('user/edit_form', array('usuario' => $usuario, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('user/edit_footer', array('usuario' => $usuario)) ?>
</div>

</div>
