<?php
// auto-generated by sfPropelAdmin
// date: 2008/12/03 01:57:06
?>
<?php echo form_tag('grupo/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($grupo, 'getIdGroup') ?>

<fieldset id="sf_fieldset_datos_de_grupo" class="">
<h2><?php echo __('Datos de Grupo') ?></h2>


<div class="form-row">
  <?php echo label_for('grupo[nombre]', __($labels['grupo{nombre}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('grupo{nombre}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('grupo{nombre}')): ?>
    <?php echo form_error('grupo{nombre}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($grupo, 'getNombre', array (
  'size' => 80,
  'control_name' => 'grupo[nombre]',
)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('Nombre del grupo') ?></div>  </div>
</div>

<div class="form-row">
  <?php echo label_for('grupo[descripcion]', __($labels['grupo{descripcion}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('grupo{descripcion}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('grupo{descripcion}')): ?>
    <?php echo form_error('grupo{descripcion}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($grupo, 'getDescripcion', array (
  'control_name' => 'grupo[descripcion]',
  'rich' => true,
)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('Descripcion corta del Grupo') ?></div>  </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_rol_asociado" class="">
<h2><?php echo __('Rol asociado') ?></h2>


<div class="form-row">
  <?php echo label_for('grupo[id_rol]', __($labels['grupo{id_rol}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('grupo{id_rol}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('grupo{id_rol}')): ?>
    <?php echo form_error('grupo{id_rol}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($grupo, 'getIdRol', array (
  'related_class' => 'Rol',
  'control_name' => 'grupo[id_rol]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('grupo' => $grupo)) ?>
<form>
</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($grupo->getIdGroup()): ?>
<?php echo button_to(__('Borrar Grupo'), 'grupo/delete?id_group='.$grupo->getIdGroup(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
