<?php
// auto-generated by sfPropelAdmin
// date: 2008/12/03 01:57:06
?>
<ul class="sf_admin_actions">
      <li><?php echo button_to(__('Agregar Grupo'), 'grupo/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
  </ul>
