<?php
// auto-generated by sfPropelAdmin
// date: 2008/12/03 01:57:06
?>
  <th id="sf_admin_list_th_nombre">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/grupo/sort') == 'nombre'): ?>
      <?php echo link_to(__('Nombre del Grupo'), 'grupo/list?sort=nombre&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/grupo/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/grupo/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Nombre del Grupo'), 'grupo/list?sort=nombre&type=asc') ?>
      <?php endif; ?>
        <?php echo image_tag(sfConfig::get('sf_admin_web_dir').'/images/help.png', array('align' => 'absmiddle', 'alt' => __('Nombre del grupo'), 'title' => __('Nombre del grupo'))) ?>  </th>
  <th id="sf_admin_list_th_descripcion">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/grupo/sort') == 'descripcion'): ?>
      <?php echo link_to(__('Descripcion del Grupo'), 'grupo/list?sort=descripcion&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/grupo/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/grupo/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Descripcion del Grupo'), 'grupo/list?sort=descripcion&type=asc') ?>
      <?php endif; ?>
        <?php echo image_tag(sfConfig::get('sf_admin_web_dir').'/images/help.png', array('align' => 'absmiddle', 'alt' => __('Descripcion corta del Grupo'), 'title' => __('Descripcion corta del Grupo'))) ?>  </th>
