<?php
// auto-generated by sfPropelAdmin
// date: 2008/12/03 01:57:06
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Datos de Grupo %%nombre%%', 
array('%%nombre%%' => $grupo->getNombre())) ?></h1>

<div id="sf_admin_header">
<?php include_partial('grupo/edit_header', array('grupo' => $grupo)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('grupo/edit_messages', array('grupo' => $grupo, 'labels' => $labels)) ?>
<?php include_partial('grupo/edit_form', array('grupo' => $grupo, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('grupo/edit_footer', array('grupo' => $grupo)) ?>
</div>

</div>
