<?php
// auto-generated by sfPropelAdmin
// date: 2008/12/03 02:29:03
?>
<?php use_helper('Object') ?>

<div class="sf_admin_filters">
<?php echo form_tag('permiso/list', array('method' => 'get')) ?>

  <fieldset>
    <h2'><?php echo __('Búsquedas') ?></h2>
    <div class="form-row">
    <label for="filters_nombre_permiso"><?php echo __('Nombre de Permiso:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[nombre_permiso]', isset($filters['nombre_permiso']) ? $filters['nombre_permiso'] : null, array (
  'size' => 15,
)) ?>
    </div>
    </div>

      </fieldset>

  <ul class="sf_admin_actions">
    <li><?php echo button_to(__('Limpiar'), 'permiso/list?filter=filter', 'class=sf_admin_action_reset_filter') ?></li>
    <li><?php echo submit_tag(__('Filtrar'), 'name=filter class=sf_admin_action_filter') ?></li>
  </ul>
<form>	
</form>
</div>
