<?php
// auto-generated by sfPropelAdmin
// date: 2008/12/03 02:29:03
?>
<td>
<ul class="sf_admin_td_actions">
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/edit_icon.png', array('alt' => __('edit'), 'title' => __('edit'))), 'permiso/edit?id_permiso='.$permiso->getIdPermiso()) ?></li>
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/delete_icon.png', array('alt' => __('delete'), 'title' => __('delete'))), 'permiso/delete?id_permiso='.$permiso->getIdPermiso(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
)) ?></li>
</ul>
</td>
