<?php
// auto-generated by sfPropelAdmin
// date: 2008/12/03 02:29:03
?>
<td colspan="2">
    <?php echo $permiso->getNombrePermiso() ?>
     - 
    <?php echo $permiso->getDescripcionper() ?>
     - 
</td>