<?php
// auto-generated by sfPropelAdmin
// date: 2008/12/03 02:29:03
?>
  <th id="sf_admin_list_th_nombre_permiso">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/permiso/sort') == 'nombre_permiso'): ?>
      <?php echo link_to(__('Nombre de Permiso'), 'permiso/list?sort=nombre_permiso&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/permiso/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/permiso/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Nombre de Permiso'), 'permiso/list?sort=nombre_permiso&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_descripcionper">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/permiso/sort') == 'descripcionper'): ?>
      <?php echo link_to(__('Descripcion del Permiso'), 'permiso/list?sort=descripcionper&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/permiso/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/permiso/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Descripcion del Permiso'), 'permiso/list?sort=descripcionper&type=asc') ?>
      <?php endif; ?>
        <?php echo image_tag(sfConfig::get('sf_admin_web_dir').'/images/help.png', array('align' => 'absmiddle', 'alt' => __('Sea lo más breve porfavor'), 'title' => __('Sea lo más breve porfavor'))) ?>  </th>
