<?php
// auto-generated by sfPropelAdmin
// date: 2008/12/03 02:29:03
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1 class='title-01'><?php echo __('Datos de Permiso %%nombre_permiso%%', 
array('%%nombre_permiso%%' => $permiso->getNombrePermiso())) ?></h1>

<div id="sf_admin_header">
<?php include_partial('permiso/edit_header', array('permiso' => $permiso)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('permiso/edit_messages', array('permiso' => $permiso, 'labels' => $labels)) ?>
<?php include_partial('permiso/edit_form', array('permiso' => $permiso, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('permiso/edit_footer', array('permiso' => $permiso)) ?>
</div>

</div>
