<?php
// auto-generated by sfPropelAdmin
// date: 2008/12/03 02:29:03
?>
<?php use_helper('I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1 class='title-01'><?php echo __('Lista de Permisos disponibles en el sistema', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('permiso/list_header', array('pager' => $pager)) ?>
<?php include_partial('permiso/list_messages', array('pager' => $pager)) ?>
</div>

<div id="sf_admin_bar">
</div>

<div id="sf_admin_content">
<?php include_partial('filters', array('filters' => $filters)) ?>
<?php if (!$pager->getNbResults()): ?>
<?php echo __('no result') ?>
<?php else: ?>
<?php include_partial('permiso/list', array('pager' => $pager)) ?>
<?php endif; ?>
<?php include_partial('list_actions') ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('permiso/list_footer', array('pager' => $pager)) ?>
</div>

</div>
