<?php
// auto-generated by sfPropelAdmin
// date: 2008/11/18 22:36:05
?>
<?php use_helper('I18N', 'Date') ?>

<?php use_stylesheet('/css/main2.css') ?>

<div id="sf_admin_container">

<h2 class="title-01"><?php echo $sf_user->getAttribute('nombrecompleto').' se muestra la información de su folder personal';?> </h2>
<?php //echo $sf_user->getAttribute('probar')?> 
<?php if ($sf_flash->has('form_error')): ?>
<h3> <?php echo $sf_flash->get('form_error') ?> </h3>
<?php endif; ?>
<?php if ($sf_flash->has('filedownload')): ?>
<h3> <?php echo $sf_flash->get('filedownload') ?> </h3>
<?php endif; ?> 
<br>
<?php for ($i = count($rutaids)-1; $i>=0; $i--){ ?>
<?php $folder=FolderPeer::retrieveByPK($rutaids[$i]); ?>
<?php echo link_to('/'.$folder->getNombreFolder(),'folder/index?idfoldernav='.$rutaids[$i].''); ?>
<?php } ?>
<br>
<br>
<div class="contenedoropciones">
<h4>Crear Folder</h4>
<form method="post" action="https://<?php echo $sf_request->getHost().'/'.$sf_request->getScriptName()?>/folder/createfolder">
<?php echo label_for('namenewfolder','Nombre');?>
<?php echo input_tag('namenewfolder'); ?>
<?php echo submit_tag('Crear Folder'); ?>
</form>
</div>

<div class="contenedoropciones">
<h4>Subir Archivo Aqui</h4>
<?php echo form_tag('folder/subirarchivo', 'multipart=true')?>
<?php //echo label_for('file','Upload')?>
<?php echo input_file_tag('file');?>
<?php echo submit_tag('Subir Archivo'); ?>
</div>
<?php if($sf_user->getAttribute('folderactual')!=$sf_user->getAttribute('folderhome')){ ?>
<div class="contenedorfoto">
<?php  echo link_to(image_tag('arriba.png'), 'folder/index?idfoldernav='.$foldersuperior)?>
<?php echo 'Subir'; ?>
</div>
<?php }?>

<?php foreach($folders as $foldeinterno){ ?>
<?php $folderbajonivel=FolderPeer::retrieveByPK($foldeinterno); ?>
<?php //echo form_tag('folder/index', 'method=get id=myfomulario2'.$folderbajonivel->getIdFolder().'')?>
<?php //echo input_hidden_tag('idfoldernav', $folderbajonivel->getIdFolder()) ?>
<div class="contenedorfoto">
<?php  echo link_to(image_tag('folder.png'), 'folder/index?idfoldernav='.$folderbajonivel->getIdFolder())?>
<?php echo ($folderbajonivel->getNombreFolder()); ?>
<br>
<?php echo link_to(image_tag('/sf/sf_admin/images/edit_icon.png', array('alt' => __('Informacion'), 'title' => __('Editar nombre de Folder'))), 'folder/updatefolder?id_updatefolder='.$folderbajonivel->getIdFolder()) ?>
<?php echo link_to(image_tag('/sf/sf_admin/images/delete_icon.png', array('alt' => __('Borar Folder'), 'title' => __('Borrar Folder'))), 'folder/deletefolder?id_deletefolder='.$folderbajonivel->getIdFolder(), array (
  'post' => true,
  'confirm' => __('Está Seguro de Eliminar el Folder?'),
)) ?>
</div>
<?php } ?>
<?php if($archivos){?>
<?php for($n=1; $n<count($archivos)+1; $n++){ ?>

<div class="contenedorfoto">

<?php  echo link_to(image_tag('/images/mime/'.$archivos[$n]['tipo'].'.png', array('alt' => __('bajar archivo'), 'title' => __('Descargar Archivo'))), 'folder/downloadarchivo?idarchivodown='.$archivos[$n]['id']) ?>
<?php echo ('<br>'.$archivos[$n]['nombre']); ?>
<br>
<?php echo link_to(image_tag('/sf/sf_admin/images/edit_icon.png', array('alt' => __('Editar Archivo'), 'title' => __('Editar datos del Archivo'))), 'archivo/editar?archivoid='.$archivos[$n]['id']) ?>
<?php echo link_to(image_tag('/sf/sf_admin/images/delete_icon.png', array('alt' => __('Borrar Archivo'), 'title' => __('Borrar Archivo'))), 'folder/deletearchivo?id_deletefile='.$archivos[$n]['id'], array (
  'post' => true,
  'confirm' => __('Está Seguro de Eliminar el Archivo?'),
)) ?>
<?php echo link_to(image_tag('download.png', array('alt' => __('bajar archivo'), 'title' => __('Descargar Archivo'))), 'folder/downloadarchivo?idarchivodown='.$archivos[$n]['id']) ?>
</div>
<?php } ?>
<?php }?>
<br>
<br>

</div>

